[package]
name = "crabots"
version = "0.1.0"
authors = ["Ilya Sheprut <optozorax@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
rand_pcg = "0.2"
bufdraw = { git = "https://github.com/optozorax/bufdraw", version = "0.1.3" }
# bufdraw = { path = "../bufdraw" }